[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.f_cpu = 240000000L

build_flags = 
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=2
  -D BOARD_HAS_PSRAM
  # TFT_eSPI Config
  -D USER_SETUP_LOADED=1
  -D ST7789_DRIVER=1
  -D TFT_WIDTH=135
  -D TFT_HEIGHT=240
  -D TFT_CS=15
  -D TFT_DC=16
  -D TFT_RST=17
  -D TFT_BL=18
  -D TFT_BACKLIGHT_ON=HIGH
  -D TFT_MOSI=11
  -D TFT_SCLK=10
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D SPI_FREQUENCY=20000000
  -D TOUCH_CS=-1
  # Watchdog config
  -D CONFIG_ESP_TASK_WDT_TIMEOUT_S=10

lib_deps = bodmer/TFT_eSPI@^2.5.0
